const colorScales = {
  // background
  backgroundCanvas: '$global.colors.backdropsWhite',
  backgroundContainer: '$global.colors.backdropsWhite',
  backgroundContainerHalftone: '$global.colors.backdropsWhiteHalfTone',
  backgroundMidgroundSubtle: '$global.colors.neutral0205',
  backgroundMidgroundMedium: '$global.colors.neutral0210',
  backgroundMidgroundDark: '$global.colors.neutral0220',
  backgroundBlanket: '$global.colors.backdropsGreyHalfTone',
  backgroundFrost: '$global.colors.backdropsWhiteFrost',
  backgroundFrostHigh: '$global.colors.backgroundFrostHigh',
  backgroundSelection: '$global.colors.blue05',

  backgroundPrimaryDefault: '$global.colors.blue60',
  backgroundPrimaryHovered: '$global.colors.blue40',
  backgroundPrimaryPressed: '$global.colors.blue70',

  backgroundSemanticGreenSubtle: '$global.colors.green05',
  backgroundSemanticGreenLight: '$global.colors.green10',
  backgroundSemanticGreenMedium: '$global.colors.green40',
  backgroundSemanticGreenDark: '$global.colors.green60',
  backgroundSemanticGreenDarkest: '$global.colors.green70',

  backgroundSemanticOrangeSubtle: '$global.colors.orange05',
  backgroundSemanticOrangeLight: '$global.colors.orange10',
  backgroundSemanticOrangeMedium: '$global.colors.orange40',
  backgroundSemanticOrangeDark: '$global.colors.orange60',
  backgroundSemanticOrangeDarkest: '$global.colors.orange70',

  backgroundSemanticRedSubtle: '$global.colors.red10',
  backgroundSemanticRedSubtler: '$global.colors.red05',
  backgroundSemanticRedLight: '$global.colors.red40',
  backgroundSemanticRedMedium: '$global.colors.red50',
  backgroundSemanticRedDark: '$global.colors.red60',
  backgroundSemanticRedDarkest: '$global.colors.red70',

  backgroundAccentBlueSubtle: '$global.colors.blue05',
  backgroundAccentBlueLight: '$global.colors.blue10',
  backgroundAccentBlueMedium: '$global.colors.blue40',
  backgroundAccentBlueDark: '$global.colors.blue60',
  backgroundAccentBlueDarker: '$global.colors.blue70',
  backgroundAccentBlueDarkest: '$global.colors.blue80',

  backgroundAccentYellowSubtle: '$global.colors.yellow05',
  backgroundAccentYellowLight: '$global.colors.yellow10',
  backgroundAccentYellowMedium: '$global.colors.yellow40',
  backgroundAccentYellowDark: '$global.colors.yellow60',
  backgroundAccentYellowDarkest: '$global.colors.yellow70',

  backgroundAccentPinkSubtle: '$global.colors.pink05',
  backgroundAccentPinkLight: '$global.colors.pink10',
  backgroundAccentPinkMedium: '$global.colors.pink40',
  backgroundAccentPinkDark: '$global.colors.pink60',
  backgroundAccentPinkDarkest: '$global.colors.pink70',

  backgroundAccentPurpleSubtle: '$global.colors.purple05',
  backgroundAccentPurpleLight: '$global.colors.purple10',
  backgroundAccentPurpleMedium: '$global.colors.purple40',
  backgroundAccentPurpleDark: '$global.colors.purple60',
  backgroundAccentPurpleDarkest: '$global.colors.purple70',

  backgroundAccentVioletSubtle: '$global.colors.violet05',
  backgroundAccentVioletLight: '$global.colors.violet10',
  backgroundAccentVioletMedium: '$global.colors.violet40',
  backgroundAccentVioletDark: '$global.colors.violet60',
  backgroundAccentVioletDarkest: '$global.colors.violet70',
  backgroundAccentVioletSelection: '$global.colors.violet60',

  backgroundAccentCyanSubtle: '$global.colors.cyan05',
  backgroundAccentCyanLight: '$global.colors.cyan10',
  backgroundAccentCyanMedium: '$global.colors.cyan40',
  backgroundAccentCyanDark: '$global.colors.cyan60',
  backgroundAccentCyanDarkest: '$global.colors.cyan70',

  backgroundNeutralDefault: '$global.colors.neutral0210',
  backgroundNeutralHovered: '$global.colors.neutral0220',
  backgroundNeutralPressed: '$global.colors.neutral0230',
  backgroundNeutralInverse: '$global.colors.neutral0170',
  backgroundNeutralInverseHovered: '$global.colors.neutral0180',
  backgroundNeutralInversePressed: '$global.colors.neutral0190',

  backgroundNeutralGrey01Subtler: '$global.colors.neutral0105',
  backgroundNeutralGrey01Subtle: '$global.colors.neutral0110',
  backgroundNeutralGrey01Light: '$global.colors.neutral0120',
  backgroundNeutralGrey01Medium: '$global.colors.neutral0140',
  backgroundNeutralGrey01Dark: '$global.colors.neutral0160',
  backgroundNeutralGrey01Darker: '$global.colors.neutral0170',
  backgroundNeutralGrey01Darkest: '$global.colors.neutral0180',

  backgroundNeutralGrey02Subtler: '$global.colors.neutral0205',
  backgroundNeutralGrey02Subtle: '$global.colors.neutral0210',
  backgroundNeutralGrey02Light: '$global.colors.neutral0220',
  backgroundNeutralGrey02Medium: '$global.colors.neutral0240',
  backgroundNeutralGrey02Dark: '$global.colors.neutral0260',
  backgroundNeutralGrey02Darker: '$global.colors.neutral0270',
  backgroundNeutralGrey02Darkest: '$global.colors.neutral0280',

  // border
  borderPrimaryDefault: '$global.colors.blue60',
  borderPrimaryHovered: '$global.colors.blue40',
  borderPrimaryPressed: '$global.colors.blue70',
  borderPrimaryFocused: '$global.colors.blue60',

  borderSemanticGreenSubtle: '$global.colors.green05',
  borderSemanticGreenLight: '$global.colors.green10',
  borderSemanticGreenMedium: '$global.colors.green40',
  borderSemanticGreenDark: '$global.colors.green60',
  borderSemanticGreenDarkest: '$global.colors.green70',

  borderSemanticOrangeSubtle: '$global.colors.orange05',
  borderSemanticOrangeLight: '$global.colors.orange10',
  borderSemanticOrangeMedium: '$global.colors.orange40',
  borderSemanticOrangeDark: '$global.colors.orange60',
  borderSemanticOrangeDarkest: '$global.colors.orange70',

  borderSemanticRedSubtler: '$global.colors.red05',
  borderSemanticRedSubtle: '$global.colors.red10',
  borderSemanticRedLight: '$global.colors.red40',
  borderSemanticRedMedium: '$global.colors.red50',
  borderSemanticRedDark: '$global.colors.red60',
  borderSemanticRedDarkest: '$global.colors.red70',

  borderAccentBlueSubtle: '$global.colors.blue05',
  borderAccentBlueLight: '$global.colors.blue10',
  borderAccentBlueMedium: '$global.colors.blue40',
  borderAccentBlueDark: '$global.colors.blue60',
  borderAccentBlueDarkest: '$global.colors.blue70',

  borderAccentYellowSubtle: '$global.colors.yellow05',
  borderAccentYellowLight: '$global.colors.yellow10',
  borderAccentYellowMedium: '$global.colors.yellow40',
  borderAccentYellowDark: '$global.colors.yellow60',
  borderAccentYellowDarkest: '$global.colors.yellow70',

  borderAccentPinkSubtle: '$global.colors.pink05',
  borderAccentPinkLight: '$global.colors.pink10',
  borderAccentPinkMedium: '$global.colors.pink40',
  borderAccentPinkDark: '$global.colors.pink60',
  borderAccentPinkDarkest: '$global.colors.pink70',

  borderAccentPurpleSubtle: '$global.colors.purple05',
  borderAccentPurpleLight: '$global.colors.purple10',
  borderAccentPurpleMedium: '$global.colors.purple40',
  borderAccentPurpleDark: '$global.colors.purple60',
  borderAccentPurpleDarkest: '$global.colors.purple70',

  borderAccentVioletSubtle: '$global.colors.violet05',
  borderAccentVioletLight: '$global.colors.violet10',
  borderAccentVioletMedium: '$global.colors.violet40',
  borderAccentVioletDark: '$global.colors.violet60',
  borderAccentVioletDarkest: '$global.colors.violet70',

  borderAccentCyanSubtle: '$global.colors.cyan05',
  borderAccentCyanLight: '$global.colors.cyan10',
  borderAccentCyanMedium: '$global.colors.cyan40',
  borderAccentCyanDark: '$global.colors.cyan60',
  borderAccentCyanDarkest: '$global.colors.cyan70',

  borderNeutralBaseSubtler: '$global.colors.neutral0220',
  borderNeutralBaseSubtle: '$global.colors.neutral0230',
  borderNeutralBaseLight: '$global.colors.neutral0250',
  borderNeutralBaseMedium: '$global.colors.neutral0270',

  borderNeutralGrey01Subtler: '$global.colors.neutral0105',
  borderNeutralGrey01Subtle: '$global.colors.neutral0110',
  borderNeutralGrey01Light: '$global.colors.neutral0120',
  borderNeutralGrey01Medium: '$global.colors.neutral0140',
  borderNeutralGrey01Dark: '$global.colors.neutral0160',
  borderNeutralGrey01Darker: '$global.colors.neutral0170',
  borderNeutralGrey01Darkest: '$global.colors.neutral0180',

  borderNeutralGrey02Subtler: '$global.colors.neutral0205',
  borderNeutralGrey02Subtle: '$global.colors.neutral0210',
  borderNeutralGrey02Light: '$global.colors.neutral0220',
  borderNeutralGrey02Medium: '$global.colors.neutral0240',
  borderNeutralGrey02Dark: '$global.colors.neutral0260',
  borderNeutralGrey02Darker: '$global.colors.neutral0270',
  borderNeutralGrey02Darkest: '$global.colors.neutral0280',

  // text
  textDefault: '$global.colors.neutral0180',
  textMain: '$global.colors.neutral0180',
  textDescription: '$global.colors.neutral0170',
  textCaption: '$global.colors.neutral0160',

  textInverseDefault: '$global.colors.neutral0110',
  textInverseMain: '$global.colors.neutral0110',
  textInverseDescription: '$global.colors.neutral0120',
  textInverseCaption: '$global.colors.neutral0150',

  textSemanticGreen: '$global.colors.green50',
  textSemanticOrange: '$global.colors.orange50',
  textSemanticRed: '$global.colors.red50',

  // icon
  iconPrimaryDefault: '$global.colors.blue60',
  iconPrimaryHovered: '$global.colors.blue50',
  iconPrimaryPressed: '$global.colors.blue70',

  iconAccentCyan: '$global.colors.cyan50',
  iconAccentPink: '$global.colors.pink50',
  iconAccentPurple: '$global.colors.purple50',
  iconAccentViolet: '$global.colors.violet50',
  iconAccentYellow: '$global.colors.yellow30',

  iconNeutralGrey01Subtler: '$global.colors.neutral0105',
  iconNeutralGrey01Subtle: '$global.colors.neutral0110',
  iconNeutralGrey01Light: '$global.colors.neutral0120',
  iconNeutralGrey01Medium: '$global.colors.neutral0140',
  iconNeutralGrey01Dark: '$global.colors.neutral0160',
  iconNeutralGrey01Darker: '$global.colors.neutral0170',
  iconNeutralGrey01Darkest: '$global.colors.neutral0180',

  iconNeutralInverse: '$global.colors.neutral0105',
  iconNeutralDefault: '$global.colors.neutral0180',
  iconNeutralSubtle: '$global.colors.neutral0120',
  iconNeutralLight: '$global.colors.neutral0150',
  iconNeutralMedium: '$global.colors.neutral0170',
  iconNeutralMain: '$global.colors.neutral0180',

  iconSemanticGreen: '$global.colors.green30',
  iconSemanticOrange: '$global.colors.orange40',
  iconSemanticRed: '$global.colors.red50',
}

export default colorScales
